### ISSUE TITLE
Broken link for Reporting bugs

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/Documentation-Issue-Tracker#32]
Link https://docs.classicpress.net/testing-classicpress/#reporting-bugs is broken via https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/class-wp-automatic-updater.php#L840

Where do the bugs get reported? A PR is needed for core file

**Comment by viktorix** [comment]
We probably should link it to issues in GitHub. That's where we want bugs reported, right?

**Comment by bahiirwa** [comment]
+1 for me. But we might have issues that are support type. How shall we handle that?

**Comment by viktorix** [comment]
The core will link to GitHub, no documentation is needed:
https://github.com/ClassicPress/ClassicPress/issues/new/choose

**Comment by bahiirwa** [comment]
PR needed for fixing https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/class-wp-automatic-updater.php#L895-L896

**Comment by viktorix** [comment]
This was fixed and merged already:
- https://github.com/ClassicPress/ClassicPress/pull/1178
